### ISSUE TITLE
Target has transitive dependencies that include static binaries:

### ISSUE THREAD

**Issue by vikmeup** [layerhq/Atlas-Messenger-iOS#199]
```
Installing Atlas (1.0.11)
Installing LayerKit (0.16.0)
```
and then I get
```
[!] The 'Pods-ProjectName' target has transitive dependencies that include static binaries: (/Users/viktor/Documents/ProjectName/Pods/LayerKit/LayerKit.embeddedframework/LayerKit.framework)
```

Using Xcode 7.0 and use_frameworks! enabled.

**Comment by inna215** [comment]
same problem.  Anyone have a solution please?

**Comment by MrMonkeyBrains** [comment]
Freshly cloned repo fails during pod install:

Atlas-Messenger-iOS (master<>)]$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Atlas (1.0.11)
Installing ClusterPrePermissions (0.7.0)
Installing LayerKit (0.16.0)
Installing SVProgressHUD (1.1.3)
[!] The 'Pods' target has transitive dependencies that include static binaries: (......code/Atlas-Messenger-iOS/Pods/LayerKit/LayerKit.embeddedframework/LayerKit.framework)

**Comment by lopsae** [comment]
Bump

**Comment by inna215** [comment]
Have you tried the new LayerKit version - 0.17 ?

**Comment by lopsae** [comment]
Thanks @inna215 
Half a workaround. Adding `pod 'LayerKit', '= 0.17.0'` to the Podfile allows Cocoapods 0.38.2 to finish. However the project does not compile in XCode 7.0.1

**Comment by inna215** [comment]
What is your error in XCode?  I just spend some time upgrading to XCode 7, finally got my project working.

**Comment by lopsae** [comment]
Several symbols not found for x86_64:

```
Undefined symbols for architecture x86_64:
  "_LYRClientObjectChangesUserInfoKey", referenced from:
  "_LYRClientObjectsDidChangeNotification", referenced from:
  "_LYRConversationDidReceiveTypingIndicatorNotification", referenced from:
  "_LYRConversationOptionsDeliveryReceiptsEnabledKey", referenced from:
  "_LYRMessageOptionsPushNotificationConfigurationKey", referenced from:
  "_LYRTypingIndicatorParticipantUserInfoKey", referenced from:
  "_LYRTypingIndicatorValueUserInfoKey", referenced from:
  "_OBJC_CLASS_$_LYRCompoundPredicate", referenced from:
  "_OBJC_CLASS_$_LYRConversation", referenced from:
  "_OBJC_CLASS_$_LYRMessage", referenced from:
  "_OBJC_CLASS_$_LYRMessagePart", referenced from:
  "_OBJC_CLASS_$_LYRPredicate", referenced from:
  "_OBJC_CLASS_$_LYRPushNotificationConfiguration", referenced from:
  "_OBJC_CLASS_$_LYRQuery", referenced from:
ld: symbol(s) not found for architecture x86_64
```

**Comment by inna215** [comment]
my errors were a little different.  Are you using the new 
use_frameworks! 

tag in your Podfile?

**Comment by seeker89** [comment]
Also having this problem, on a fresh project with 
```
platform :ios, '9.0'
use_frameworks!
pod "LayerKit", "~> 0.17.0"
pod 'Atlas', '~> 1.0.13'
```
```
Undefined symbols for architecture x86_64:
  "_LYRClientObjectChangesUserInfoKey", referenced from:
      -[ATLConversationViewController layerClientObjectsDidChange:] in ATLConversationViewController.o
  "_LYRClientObjectsDidChangeNotification", referenced from:
      -[ATLConversationViewController atl_registerForNotifications] in ATLConversationViewController.o
  "_LYRConversationDidReceiveTypingIndicatorNotification", referenced from:
      -[ATLConversationViewController atl_registerForNotifications] in ATLConversationViewController.o
  "_LYRConversationOptionsDeliveryReceiptsEnabledKey", referenced from:
      -[ATLConversationViewController conversationWithParticipants:] in ATLConversationViewController.o
  "_LYRMessageOptionsPushNotificationConfigurationKey", referenced from:
      _ATLMessageForParts in ATLMessagingUtilities.o
  "_LYRTypingIndicatorParticipantUserInfoKey", referenced from:
      -[ATLConversationViewController didReceiveTypingIndicator:] in ATLConversationViewController.o
  "_LYRTypingIndicatorValueUserInfoKey", referenced from:
      -[ATLConversationViewController didReceiveTypingIndicator:] in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRCompoundPredicate", referenced from:
      objc-class-ref in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRConversation", referenced from:
      objc-class-ref in ATLConversationListViewController.o
      objc-class-ref in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRMessage", referenced from:
      objc-class-ref in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRMessagePart", referenced from:
      objc-class-ref in ATLMessagingUtilities.o
  "_OBJC_CLASS_$_LYRPredicate", referenced from:
      objc-class-ref in ATLConversationListViewController.o
      objc-class-ref in ATLConversationViewController.o
  "_OBJC_CLASS_$_LYRPushNotificationConfiguration", referenced from:
      objc-class-ref in ATLMessagingUtilities.o
  "_OBJC_CLASS_$_LYRQuery", referenced from:
      objc-class-ref in ATLConversationListViewController.o
      objc-class-ref in ATLConversationViewController.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by blakewatters** [comment]
`use_frameworks!` is now fully supported with LayerKit v0.17.0

**Comment by nishantdongare** [comment]
Still facing the same issue by @seeker89

**Comment by immexerxez** [comment]
Having same issue cocoapods 0.39.0, layerkit 0.17.0, atlas 1.0.13 with tag use_frameworks!
