### ISSUE TITLE
Not compile

### ISSUE THREAD

**Issue by brianchu** [layerhq/Atlas-Messenger-iOS#224]
First, the pod has problem:
$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.5 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `Atlas` from `Libraries/Atlas`
[!] No podspec found for `Atlas` in `Libraries/Atlas`brian.chu@bchu-ml:~/private/turnstile/layer/Atlas-Messenger-iOS (master)$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.5 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `Atlas` from `Libraries/Atlas`
[!] No podspec found for `Atlas` in `Libraries/Atlas`

I remove the 'Libraries/Altas' part and run pod update successfully.

but then when trying to compile in Xcode 7.2.1
Errors:
/Users/brian.chu/private/turnstile/layer/Atlas-Messenger-iOS/Code/ATLMAppDelegate.m:159:47: Implicit declaration of function 'ATLDefaultUserNotificationCategory' is invalid in C99
/Users/brian.chu/private/turnstile/layer/Atlas-Messenger-iOS/Code/ATLMAppDelegate.m:159:47: Implicit conversion of 'int' to 'id _Nonnull' is disallowed with ARC
/Users/brian.chu/private/turnstile/layer/Atlas-Messenger-iOS/Code/ATLMAppDelegate.m:159:47: Incompatible integer to pointer conversion sending 'int' to parameter of type 'id _Nonnull'
/Users/brian.chu/private/turnstile/layer/Atlas-Messenger-iOS/Code/ATLMAppDelegate.m:245:37: Use of undeclared identifier 'ATLUserNotificationInlineReplyActionIdentifier'

**Comment by feifanzhou** [comment]
Hi @brianchu 
Thanks for reporting this. Check out the PR for the fix. If you have an existing project, you might want to manually apply the fix:

1. Edit the submodule URL in `.gitmodules` to use the HTTPS URL
2. `git submodule sync` to register the new submodule URL
3. `git submodule update` to clone the submodule
4. `pod install`
5. Open/run as expected

**Comment by brianchu** [comment]
It works. Thanks. You may want to update the README.md too.
