### ISSUE TITLE
Not working with Layer Kit 0.22

### ISSUE THREAD

**Issue by DevangiDesai** [layerhq/Atlas-Messenger-iOS#239]
Atlas-Messenger-iOS/Code/ATLMAppDelegate.m:103:49: No known class method for selector 'clientWithAppID:options:'
Atlas-Messenger-iOS/Code/ATLMAppDelegate.m:103:104: Use of undeclared identifier ‘LYRClientOptionSynchronizationPolicy'
Atlas-Messenger-iOS/Code/ATLMAppDelegate.m:103:145: Use of undeclared identifier 'LYRClientSynchronizationPolicyMessageCount'

Atlas-Messenger-iOS/Pods/Atlas/Code/Controllers/ATLConversationViewController.m:596:44: Use of undeclared identifier ‘LYRTypingDidBegin'

**Comment by aforarup** [comment]
Facing the same problem.

**Comment by seanj** [comment]
+1

**Comment by feifanzhou** [comment]
This has been fixed for a while — the latest release of Atlas and `master` on both Atlas and this repo have been updated.
